### ISSUE TITLE
Add CONTRIBUTING.md file for CONTRIBUTING code 

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/Open-GL#2]
* Add a simple CONTRIBUTING guideline for people looking to contribute code to this repository! Sample templates can be taken and modified according to convenience!

**This Issue is open up for grabs only for first timers who haven't sent a PR yet! If you have already sent a PR, kindly avoid resolving this Issue! The Issue can be claimed by mentioning "I Claim!" in the comments below!**

**Comment by rishabh-bansal** [comment]
I Claim!
