### ISSUE TITLE
Add Code of Conduct for Developers

### ISSUE THREAD

**Issue by salman-bhai** [salman-bhai/Open-GL#3]
* Add a sample Code of Conduct for contributors mentioning about community guidelines.

**This Issue is open up for grabs only for first timers who haven't sent a PR yet! If you have already sent a PR, kindly avoid resolving this Issue! The Issue can be claimed by mentioning "I Claim!" in the comments below!**

**Comment by rishabh-bansal** [comment]
I Claim! #4

**Comment by salman-bhai** [comment]
Go ahead send a PR! :stuck_out_tongue:

**Comment by salman-bhai** [comment]
The Previous PR didnt have that file @rishabh-bansal

**Comment by rishabh-bansal** [comment]
I will add one, but Hacktoberfes will start from October, can I PR in October?

**Comment by salman-bhai** [comment]
If someone else claims and resolves I'll have to assign it to them! Sorry man :face_with_head_bandage:

**Comment by rishabh-bansal** [comment]
#5 PR made
